import { papers, screenplayWorks } from './english-copy.js';
export const categories = [
  { id: 'writing', channel: '01', title: 'RESEARCH PAPERS', en: 'PAPERS / RESEARCH', color: '#b8ccec', tag: 'PAPERS / RESEARCH', intro: 'Unfold a letter to read the research.', projects: papers.map((w, i) => ({ ...w, id: `letter-${i + 1}`, description: w.summary, role: 'AUTHOR / WU XITING' })) },
  { id: 'script', channel: '02', title: 'SCREENPLAYS', en: 'SCRIPTS / TRAIN WINDOW', color: '#b8ccec', tag: 'SCRIPTS / TRAIN WINDOW', intro: 'Move the view beyond the train window. Stop at a story.', projects: screenplayWorks.map(w=>({...w,description:w.summary})) },
  { id: 'visual', channel: '03', title: 'VISUAL ART', en: 'VISUAL STORIES', color: '#b8dacf', tag: 'GRAPHIC / IDENTITY', intro: 'A collection of color, character, and changing seasons.', projects: [
    {"id": "spring", "title": "SPRING", "en": "SPRING", "kind": "FOUR SEASONS / ILLUSTRATION", "description": "Four Seasons illustration / Spring", "role": "ARTWORK / WU XITING", "note": "", "cover": "images/seasons/spring.jpg", "previewCover": "images/seasons/covers/spring.png"},
    {"id": "summer", "title": "SUMMER", "en": "SUMMER", "kind": "FOUR SEASONS / ILLUSTRATION", "description": "Four Seasons illustration / Summer", "role": "ARTWORK / WU XITING", "note": "", "cover": "images/seasons/summer.jpg", "previewCover": "images/seasons/covers/summer.png"},
    {"id": "autumn", "title": "AUTUMN", "en": "AUTUMN", "kind": "FOUR SEASONS / ILLUSTRATION", "description": "Four Seasons illustration / Autumn", "role": "ARTWORK / WU XITING", "note": "", "cover": "images/seasons/autumn.jpg", "previewCover": "images/seasons/covers/autumn-flow-v3.png"},
    {"id": "winter", "title": "WINTER", "en": "WINTER", "kind": "FOUR SEASONS / ILLUSTRATION", "description": "Four Seasons illustration / Winter", "role": "ARTWORK / WU XITING", "note": "", "cover": "images/seasons/winter.jpg", "previewCover": "images/seasons/covers/winter-corrected.png"},
    {"id": "study-05", "title": "STUDY 05", "en": "STUDY 05", "kind": "UNTITLED ILLUSTRATION", "description": "Illustration study 05", "role": "ARTWORK / WU XITING", "note": "", "cover": "images/artworks/study-05.jpg", "previewCover": "images/artworks/covers/study-05.png"},
    {"id": "study-06", "title": "STUDY 06", "en": "STUDY 06", "kind": "UNTITLED ILLUSTRATION", "description": "Illustration study 06", "role": "ARTWORK / WU XITING", "note": "", "cover": "images/artworks/study-06.jpg", "previewCover": "images/artworks/covers/study-06.png"},
    {"id": "study-07", "title": "STUDY 07", "en": "STUDY 07", "kind": "UNTITLED ILLUSTRATION", "description": "Illustration study 07", "role": "ARTWORK / WU XITING", "note": "", "cover": "images/artworks/study-07.jpg", "previewCover": "images/artworks/covers/study-07.png"},
    {"id": "study-08", "title": "STUDY 08", "en": "STUDY 08", "kind": "UNTITLED ILLUSTRATION", "description": "Illustration study 08", "role": "ARTWORK / WU XITING", "note": "", "cover": "images/artworks/study-08.jpg", "previewCover": "images/artworks/covers/study-08.png"},
  ] },
  { id: 'image', channel: '04', title: 'MOTION FILMS', en: 'FRAGMENTS OF LIGHT', color: '#9eb9db', tag: 'IMAGE / MOTION', intro: 'Three films made from moments in motion.', projects: [
    {"id": "hpv", "title": "GAME OF LIFE / HPV PREVENTION", "en": "GAME OF LIFE / HPV", "kind": "HEALTH FILM", "description": "A game-inspired short film about HPV prevention.", "role": "ORIGINAL VIDEO / WU XITING", "note": "", "video": "videos/hpv.mp4", "cover": "images/video-covers/hpv.jpg", "previewCover": "images/video-covers/hpv-poster.jpg", "discCover": "images/video-covers/template/hpv-frame.jpg"},
    {"id": "campus-band", "title": "CAMPUS BAND", "en": "CAMPUS BAND", "kind": "DOCUMENTARY", "description": "A live-action documentary following a campus band.", "role": "GROUP PRODUCTION / WU XITING", "note": "", "video": "videos/campus-band.mp4", "cover": "images/video-covers/campus-band.jpg", "previewCover": "images/video-covers/campus-band-poster.jpg", "discCover": "images/video-covers/template/campus-band-frame.jpg"},
    {"id": "kexinrou", "title": "KEXINROU", "en": "KEXINROU", "kind": "BRAND FILM", "description": "A live-action commercial for Kexinrou.", "role": "ORIGINAL VIDEO / WU XITING", "note": "", "video": "videos/kexinrou.mp4", "cover": "images/video-covers/kexinrou.jpg", "previewCover": "images/video-covers/kexinrou-poster.jpg", "discCover": "images/video-covers/template/kexinrou-frame.jpg"},
  ] },
];
export const channelMap = {"1":3,"2":2,"3":1,"4":1,"5":0,"6":3,"7":0,"8":1,"9":0,"10":2,"11":0,"12":1,"13":2,"14":3,"15":0,"16":1,"17":3,"18":3,"19":0,"20":2,"21":0,"22":2,"23":1};
export const categoryForScreen = name => categories[channelMap[Number(name.match(/TV_(\d+)/)?.[1])]];
