import gsap from 'gsap';
import './resume.css';

const projects = [
  {date:'AUG 2026 — PRESENT',title:'Learning through virtual worlds',role:'Research & interaction concept',status:'RESEARCH IN PROGRESS',summary:'An environmental-storytelling framework for self-directed science learning among teenagers.',details:['Developing questionnaires and needs research around learning motivation, interactive feedback and knowledge exploration.','Planning a virtual interaction prototype to investigate how spatial clues and task feedback can make science learning more engaging.']},
  {date:'SEP 2024 — PRESENT',title:'Qianli Tongqian',role:'Independent developer & interaction designer',status:'INTERACTIVE WEB APP',summary:'Turning I Ching reasoning into an interactive system that visitors can explore, compare and reflect on.',details:['Designed six modules: divination, hexagram self-assessment, history, library, a local diary prototype and a personal area. Built the information architecture, interface and responsive frontend.','Rebuilt an early Flutter/Dart prototype with HTML, CSS and JavaScript. Normalized 64 hexagrams and 384 lines, corrected mapping errors and implemented rules for classification and scoring.','Added ARIA, visible focus and reduced-motion support, SVG and WebAudio interactions, plus offline persistence with LocalStorage and JSON import/export. Historical sources remain traceable; the custom four-coin rules are identified as original adaptations.']},
  {date:'MAR — MAY 2025',title:'Library management prototype',role:'Full-stack developer',status:'DATABASE / BACKEND',summary:'A small lending system built around clear data relationships, business rules and API checks.',details:['Designed a three-table SQLite model for books, readers and loans, including business-state constraints.','Built 13 Node.js endpoints for borrowing, returns, stock checks, overdue restrictions and reader-data protection.','Standardized urlencoded request bodies, repaired create/edit/search forms and wrote an API smoke-test script for boundary cases.']},
  {date:'JAN — AUG 2025',title:'Who Is Guilty?',role:'Independent writer & game developer',status:'IN DEVELOPMENT',summary:'A 2D branching narrative game with a playable vertical slice, built in RPG Maker MZ.',details:['Designed the world, character relationships and an e01–e64 branching framework, with four positive and three negative endings planned.','The current slice contains two main maps and more than 130 event nodes, including collision and scene events. It represents a development milestone, not a finished game.','Implemented conditions, scene changes, lighting, investigation records and save/load, with a custom JavaScript plugin. Main-route, hearing-aid branch, collision, lighting and save/load checks are automated.','Keyword rebuttals, voting, additional maps and ending sequences remain planned.']},
  {date:'JUL 2023 — PRESENT',title:'Independent creative-goods shop',role:'End-to-end shop operator',status:'COMMERCE / USER INSIGHT',summary:'An anime and Chinese-style merchandise shop on Xianyu, operated from product selection to customer support.',details:['Managed listings, promotional content, customer communication and after-sales service. Recorded 3,000+ orders, CNY 180,000+ in sales revenue and a 100% positive-feedback rate.','Used Python and jieba for keyword segmentation and frequency counts, then manually grouped related needs and review themes.','Used SnowNLP for initial sentiment screening and compared search interest, repeat purchases and critical feedback to inform product ranking and community content.']},
  {date:'MAY 2025',title:'HPV prevention campaign',role:'Planning & editing',status:'AWARD / FILM',summary:'A campaign entry for the MSD HPV advertising competition.',details:['Received an Excellence Award in the National College Student Advertising Art Festival Academy Awards.','Contributed campaign planning and video editing. The film is part of this portfolio’s motion archive.']},
  {date:'APR 2025 — PRESENT',title:'AI-assisted visual storytelling',role:'Independent creator',status:'VISUAL NARRATIVE',summary:'A five-stage workflow connecting character development, storyboards, shot design, motion references and editing.',details:['Created three series/short-film projects while exploring character consistency and visual continuity, with human and model contributions identified.','Produced a 20.25-second live-action/animation concept advertisement and a 60-second Xichang travel vlog combining location footage and AI animation; developed storyboard scripts.','Checked codecs, frame rates, loudness and true peak, and reviewed generated brand lettering, shot continuity and audio manually.','Character promotional-video material remains at the concept/reference stage. Organized character, scene, UI and audio assets with consistent naming, dimensions and style. Doubao supported ideation and shot descriptions; final selection and delivery decisions remained my own.']},
];
const experience=[
 {date:'FEB — MAR 2026',title:'UI / Frontend Intern',place:'Chengdu Hubu Network Technology',body:'Supported product UI iterations, page and component implementation, styling, data-display integration and interaction fixes.',points:['Practiced responsive H5 layouts, Flutter adaptation, API integration, browser debugging and state updates.','Applied component decomposition and data-driven views to personal projects. Studied basic MySQL/MSSQL table design and queries, and traced field, null-value and data-type mismatches between APIs and interfaces.']},
 {date:'JUL — AUG 2025',title:'Information Technology Intern',place:'Sichuan Admissions & Examination Guidance Center',body:'Contributed to website maintenance, content updates, form checks and basic functional verification.',points:['Used Python for spreadsheet organization and data validation, later applying the same methods to personal projects.','Built a maintenance workflow around reproducing issues, checking data, locating causes and verifying changes.']},
];
const publications=['New Media Culture and Globalization','The Cultural Value of Contemporary Documentaries','Technology, New Media and Social Change','Ethics and the Rule of Law in Digital New Media','Development Trends in Contemporary Documentaries','The Social Impact of Anime-Related Consumption through Allowance Spending','Paradoxes from a Logical Perspective'];
const nav=[['profile','PROFILE'],['education','EDUCATION'],['projects','PROJECTS'],['experience','EXPERIENCE'],['skills','SKILLS'],['writing','WRITING & AWARDS'],['contact','CONTACT']];

export function openResume({onClose,reduced=false,trigger}) {
 const previous=document.activeElement,origin=trigger?.getBoundingClientRect();
 const dialog=document.createElement('dialog');dialog.className='cv-space';dialog.setAttribute('aria-labelledby','cv-name');
 dialog.innerHTML=`<header class="cv-top"><span>SHI PIN / PERSONAL FILE</span><span class="cv-scroll-status">SCROLL TO EXPLORE ↓</span><button class="cv-close" aria-label="Close resume">BACK TO SIGNAL ↗</button><i class="cv-progress"></i></header>
 <div class="cv-layout"><aside class="cv-side"><span class="cv-eyebrow">ABOUT / CURRICULUM VITAE</span><h1 id="cv-name">WU<br>XITING<span>TINA</span></h1><p>Media. Interaction.<br>Stories made tangible.</p><span class="cv-location">CHENGDU, CHINA</span><nav aria-label="Resume sections">${nav.map(([id,label],i)=>`<a href="#cv-${id}"><span>0${i+1}</span>${label}</a>`).join('')}</nav><a class="cv-mail" href="mailto:23846687@qq.com">LET’S CONNECT ↗</a><button class="cv-print">PRINT / SAVE PDF ↓</button></aside>
 <main class="cv-content"><section id="cv-profile" class="cv-section"><span class="cv-eyebrow">01 / PROFILE</span><h2>Between storytelling<br>and interaction<span class="cv-cursor">_</span></h2><p class="cv-intro">I study Radio and Television Directing at Sichuan University, with a minor in Software Engineering. My work moves between writing, visual storytelling and interactive systems.</p><p>I build web and narrative-game prototypes, make films and illustrations, and explore how people engage with stories through interfaces and spaces.</p><div class="cv-tags"><span>MEDIA & NARRATIVE</span><span>INTERACTION DESIGN</span><span>WEB DEVELOPMENT</span></div><div class="cv-profile-note"><span>SCROLL TO READ THE FILE</span><span>↓</span></div></section>
 <section id="cv-education" class="cv-section"><span class="cv-eyebrow">02 / EDUCATION</span><h2>Sichuan University</h2><p class="cv-date">SEP 2023 — JUL 2027 / EXPECTED GRADUATION</p><div class="cv-education-grid"><article><h3>Radio & Television Directing</h3><span>MAJOR</span><strong>3.8 <small>/ 4.0 GPA</small></strong><p>Average score: 88.76</p></article><article><h3>Software Engineering</h3><span>MINOR</span><strong>3.0 <small>/ 4.0 GPA</small></strong><p>Average score: 79.13</p></article></div><p>Comprehensive Third-Class Scholarship · CET-6 English qualification</p><details class="cv-details"><summary>SELECTED COURSEWORK <span>+</span></summary><p>New Media Practice (95), Web Multimedia Design (95), Short Video & IP Creativity (95), Media, Public Opinion & Communication (92), Foundations of Film & Television Art (91).</p><p>Software coursework: Data Structures, Programming, Operating Systems, Database Systems, Computer Networks and Computer Organization.</p></details></section>
 <section id="cv-projects" class="cv-section"><span class="cv-eyebrow">03 / SELECTED PROJECTS</span><h2>Ideas into practice.</h2><div class="cv-timeline">${projects.map((p,i)=>`<article class="cv-entry"><span class="cv-date">${p.date}</span><span class="cv-tag">${p.status}</span><h3>${p.title}</h3><p class="cv-role">${p.role}</p><p>${p.summary}</p><details class="cv-details"><summary>PROJECT NOTES <span>+</span></summary><ul>${p.details.map(t=>`<li>${t}</li>`).join('')}</ul></details></article>`).join('')}</div></section>
 <section id="cv-experience" class="cv-section"><span class="cv-eyebrow">04 / EXPERIENCE</span><h2>Learning by doing.</h2>${experience.map(e=>`<article class="cv-entry"><span class="cv-date">${e.date}</span><h3>${e.title}</h3><p class="cv-role">${e.place}</p><p>${e.body}</p><ul>${e.points.map(p=>`<li>${p}</li>`).join('')}</ul></article>`).join('')}</section>
 <section id="cv-skills" class="cv-section"><span class="cv-eyebrow">05 / SKILLS & TOOLS</span><h2>A working toolkit.</h2>${[['DEVELOPMENT','JavaScript / HTML / CSS','Dart / Flutter','Node.js / SQLite','Relational database modeling','REST-style APIs / automated API checks'],['INTERACTION','Accessible web interfaces','RPG Maker JavaScript plugins','2D narrative prototypes','SVG / WebAudio'],['CREATIVE PRACTICE','Information architecture','Visual guidelines','Branching screenplay writing','Human–AI production workflows','Adobe Premiere Pro'],['WORKFLOW','Git','Test scripting','Python data preparation']].map(([title,...skills])=>`<article class="cv-skill-group"><h3>${title}</h3><div class="cv-tags">${skills.map(s=>`<span>${s}</span>`).join('')}</div></article>`).join('')}</section>
 <section id="cv-writing" class="cv-section"><span class="cv-eyebrow">06 / WRITING & RECOGNITION</span><h2>Beyond the interface.</h2><article class="cv-entry"><span class="cv-date">MAY 2025 — MAR 2026</span><h3>Published essays</h3><p>“My Mum Is a Flower Enthusiast” and “Planting Spring with Mum in the Wilderness,” published in <em>Education Herald</em> and <em>Admissions & Examination News</em>, respectively.</p></article><details class="cv-details"><summary>UNPUBLISHED PAPERS <span>+</span></summary><ul>${publications.map(p=>`<li>${p}</li>`).join('')}</ul></details><article class="cv-entry"><span class="cv-date">JUN 2024</span><h3>Outstanding Volunteer</h3><p>Recognized for assisting applicants and parents at an in-person university admissions consultation event in Sichuan.</p></article></section>
 <section id="cv-contact" class="cv-section cv-contact"><span class="cv-eyebrow">07 / CONTACT</span><h2>Continue the<br>conversation.</h2><a href="mailto:23846687@qq.com">23846687@qq.com ↗</a><a href="tel:+8613608642508">+86 136 0864 2508 ↗</a><p>Chengdu, Sichuan, China</p><span class="cv-file-end">END OF FILE / THANKS FOR TUNING IN.</span></section></main></div>`;
 document.body.append(dialog);dialog.showModal();dialog.querySelector('.cv-close').focus({preventScroll:true});
 let closed=false,raf=0;
 const sections=[...dialog.querySelectorAll('.cv-section')],links=[...dialog.querySelectorAll('.cv-side nav a')];
 function update(){raf=0;const max=dialog.scrollHeight-dialog.clientHeight,progress=max>0?dialog.scrollTop/max:0;dialog.querySelector('.cv-progress').style.transform=`scaleX(${progress})`;let active=0;sections.forEach((s,i)=>{if(s.getBoundingClientRect().top<innerHeight*.42)active=i;});links.forEach((l,i)=>{if(i===active)l.setAttribute('aria-current','location');else l.removeAttribute('aria-current');});dialog.querySelector('.cv-scroll-status').textContent=`${String(Math.round(progress*100)).padStart(2,'0')}% / ${nav[active][1]}`;}
 const onScroll=()=>{if(!raf)raf=requestAnimationFrame(update);};dialog.addEventListener('scroll',onScroll,{passive:true});
 const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}});},{root:dialog,threshold:.04});
 sections.forEach(s=>{if(reduced)s.classList.add('is-visible');else observer.observe(s);});
 links.forEach(l=>l.addEventListener('click',e=>{e.preventDefault();dialog.querySelector(l.getAttribute('href')).scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});}));
 let printState=[];
 const beforePrint=()=>{printState=[...dialog.querySelectorAll('details')].map(el=>[el,el.open]);printState.forEach(([el])=>el.open=true);};
 const afterPrint=()=>{printState.forEach(([el,open])=>el.open=open);printState=[];update();};
 window.addEventListener('beforeprint',beforePrint);window.addEventListener('afterprint',afterPrint);
 dialog.querySelector('.cv-print').onclick=()=>window.print();
 function close(){if(closed)return;closed=true;window.removeEventListener('beforeprint',beforePrint);window.removeEventListener('afterprint',afterPrint);observer.disconnect();cancelAnimationFrame(raf);dialog.removeEventListener('scroll',onScroll);gsap.killTweensOf(dialog);dialog.close();dialog.remove();onClose();if(previous?.isConnected)previous.focus({preventScroll:true});}
 dialog.querySelector('.cv-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 if(!reduced&&origin){gsap.fromTo(dialog,{clipPath:`inset(${origin.top}px ${Math.max(0,innerWidth-origin.right)}px ${Math.max(0,innerHeight-origin.bottom)}px ${origin.left}px)`,opacity:.5},{clipPath:'inset(0px 0px 0px 0px)',opacity:1,duration:.75,ease:'power3.inOut',onComplete:()=>{dialog.style.clipPath='none';}});}
 update();return close;
}
